[package]
name = "rocm_lib_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.147"

[build-dependencies]
cmake = "0.1.31"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[features]
vendored = []